knpu_oauth2_client:
    clients:
        google:
            type: google
            client_id: '%env(GOOGLE_CLIENT_ID)%'
            client_secret: '%env(GOOGLE_CLIENT_SECRET)%'
            redirect_route: auth_social_callback
            redirect_params: { provider: google }

        discord:
            type: discord
            client_id: '%env(DISCORD_CLIENT_ID)%'
            client_secret: '%env(DISCORD_CLIENT_SECRET)%'
            redirect_route: auth_social_callback
            redirect_params: { provider: discord }

        github:
            type: github
            client_id: '%env(GITHUB_CLIENT_ID)%'
            client_secret: '%env(GITHUB_CLIENT_SECRET)%'
            redirect_route: auth_social_callback
            redirect_params: { provider: github }

        spotify:
            type: spotify
            client_id: '%env(SPOTIFY_CLIENT_ID)%'
            client_secret: '%env(SPOTIFY_CLIENT_SECRET)%'
            redirect_route: auth_social_callback
            redirect_params: { provider: spotify }
